version: '3'

#volumes:
#  keycloak-theme:
#    driver: local
  
services:
  keycloak:
      image: jboss/keycloak
      volumes:
        - .:/opt/jboss/keycloak/themes/lojing-theme
        - ./standalone/configuration/standalone-ha.xml:/opt/jboss/keycloak/standalone/configuration/standalone-ha.xml
      environment:
        CONTAINER_NAME: keycloak
        KEYCLOAK_USER: admin
        KEYCLOAK_PASSWORD: admin
        # Uncomment the line below if you want to specify JDBC parameters. The parameter below is just an example, and it shouldn't be used in production without knowledge. It is highly recommended that you read the PostgreSQL JDBC driver documentation in order to use it.
        #JDBC_PARAMS: "ssl=true"
      ports:
        - 9000:8080
